# Generated by Django 3.0.8 on 2020-07-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('emailaddress', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('iam', models.CharField(choices=[(' Entrepreneur   ', 'Entrepreneur'), (' Businessman', ' Businessman'), ('Investor', 'Investor'), ('Freelancers', 'Freelancers'), ('Students', 'Students'), (' student entrepreneur', ' student entrepreneur')], max_length=50)),
                ('profile', models.CharField(choices=[('  startup idea  , startup , join startup as a cofounder, join startup as a team member ', 'startup idea  , startup , join startup as a cofounder, join startup as a team member'), (' company  /firm , franchisee  , Distributors   , wholesalers  ,  investor ', ' company  /firm , franchisee  , Distributors   , wholesalers  ,  investor '), ('investor', 'investor'), ('Freelancers', 'Freelancers'), ('Internship/ job seeker  / freelancing work  / all entrepreneur categories ', ' Internship/ job seeker  / freelancing work  / all entrepreneur categories '), (' all categories of students and entrepreneur ', ' all categories of students and entrepreneur')], max_length=100)),
                ('profielpic', models.ImageField(upload_to='images')),
                ('address', models.TextField(max_length=100)),
                ('contactno', models.CharField(max_length=15)),
                ('country', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=100)),
            ],
        ),
    ]
