# Generated by Django 3.0.8 on 2020-07-13 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='profielpic',
            new_name='profilepic',
        ),
    ]
