# Generated by Django 3.0.8 on 2020-07-13 06:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200713_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='lookingfor',
            field=models.CharField(choices=[(' Entrepreneur   ', 'Entrepreneur'), (' Businessman', ' Businessman'), ('Investor', 'Investor'), ('Freelancers', 'Freelancers'), ('Students', 'Students'), (' student entrepreneur', ' student entrepreneur')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
